### ISSUE TITLE
Spanish Translations

### ISSUE THREAD

**Issue by LuigiBaute** [martysweet/cfn-lint#112]
hello I would like to collaborate with your Spanish translator project which is my native language, I could translate any text

**Comment by LuigiBaute** [comment]
hello I would like to collaborate with your Spanish translator project which is my native language, I could translate any text

**Comment by martysweet** [comment]
Hi @LuigiBaute,

Thanks for your interest in the project. The main document for this project is the [README.md](https://github.com/martysweet/cfn-lint/blob/master/README.md).

For now, to enable future updates to a file and understanding by maintainers who are not Spanish, would it be possible to label each section header as follows.

```
...
[//]: # (Translation Section: What can cfn-lint do?)
### ¿Qué puede hacer cfn-lint?
...
```
A pull request with a file of README_es.MD, would be great!

If you know any better tools/techniques for this, it would be nice to discuss.

Thanks,
Marty

**Comment by LuigiBaute** [comment]
Ok I'll do it exactly as you asked!

**Comment by LuigiBaute** [comment]
is this what you meant?:

# cfn-lint [![CircleCI](https://img.shields.io/circleci/project/github/martysweet/cfn-lint.svg)](https://circleci.com/gh/martysweet/cfn-lint) [![npm version](https://badge.fury.io/js/cfn-lint.svg)](https://www.npmjs.com/package/cfn-lint) [![npm](https://img.shields.io/npm/dm/cfn-lint.svg)](https://www.npmjs.com/package/cfn-lint)

[//]: # (Translation Section: A more friendly CloudFormation JSON and YAML Validator)
#### Un validador para CloudFormation JSON and YAML más amigable.
[//]: # (cfn-lint is a tool used to improve your CloudFormation development cycle.
If you are here, you are probably fed up of waiting for 10 minutes or more before CloudFormation gives you an error due to a typo. 
This tool aims to remove that waste of time. The tool takes the CloudFormation template,
and resolves all the Intrinsic functions defined before checking the Properties of Resources defined.)

`cfn-lint` es una herramienta utilizada para mejorar tu ciclo de desarrollo en CloudFormation. Si estás aquí, probablemente estés 
harto de esperar 10 minutos o más antes de que CloudFormation te dé un error debido a un error gramatical. Esta herramienta tiene como objetivo eliminar esa pérdida de tiempo. 
La herramienta toma el modelo de CloudFormation,y resuelve todas las funciones intrínsecas definidas antes de verificarlas _Propiedades_ de los _Recursos_ definidos.
La herramienta puede usarse sobre la línea de comando usando `cfn-lint`, o puede usarse como un módulo dentro de otra aplicación de JavaScript.

[//]: # (translation section: Note: This tool is currently case-sensitive in relation to AWS CloudFormation types, for example aws::lambda::function != AWS::Lambda::Function.)

#* _Nota: actualmente, esta herramienta distingue entre mayúsculas y minúsculas en relación con los tipos AWS CloudFormation, por ejemplo aws::lambda::function != AWS::Lambda::Function._*

[//]: # (translation section:## Installation)

## Instalación

**Comment by martysweet** [comment]
Hi @LuigiBaute, just the comments for each header should be fine.

```
# cfn-lint [![CircleCI](https://img.shields.io/circleci/project/github/martysweet/cfn-lint.svg)](https://circleci.com/gh/martysweet/cfn-lint) [![npm version](https://badge.fury.io/js/cfn-lint.svg)](https://www.npmjs.com/package/cfn-lint) [![npm](https://img.shields.io/npm/dm/cfn-lint.svg)](https://www.npmjs.com/package/cfn-lint)

[//]: # (Translation Section: A more friendly CloudFormation JSON and YAML Validator)
#### Un validador para CloudFormation JSON and YAML más amigable.
`cfn-lint` es una herramienta utilizada para mejorar tu ciclo de desarrollo en CloudFormation. Si estás aquí, probablemente estés 
harto de esperar 10 minutos o más antes de que CloudFormation te dé un error debido a un error gramatical. Esta herramienta tiene como objetivo eliminar esa pérdida de tiempo. 
La herramienta toma el modelo de CloudFormation,y resuelve todas las funciones intrínsecas definidas antes de verificarlas _Propiedades_ de los _Recursos_ definidos.
La herramienta puede usarse sobre la línea de comando usando `cfn-lint`, o puede usarse como un módulo dentro de otra aplicación de JavaScript.

#* _Nota: actualmente, esta herramienta distingue entre mayúsculas y minúsculas en relación con los tipos AWS CloudFormation, por ejemplo aws::lambda::function != AWS::Lambda::Function._*

[//]: # (Translation Section: Installation)
## Instalación
```

Thanks!
