### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by RazzM13** [martysweet/cfn-lint#119]
I was just trying to replicate the build environment for this project and I've discovered that the project will not build.

Steps to replicate:
1) `git checkout 2c5ff5dfac7d6962a68c08ee1bd16abeb2667c4f`
2) `npm install`
Output: [npm_install.log](https://github.com/martysweet/cfn-lint/files/1852699/npm_install.log)
3) `npm run build`
Output: [npm_build.log](https://github.com/martysweet/cfn-lint/files/1852701/npm_build.log)

Expected: The `npm run build` to succeed without an error and to return a 0 exit code.

**Comment by RazzM13** [comment]
After some investigation, I believe that the fault lies with the version of the *@types/colors* package.

**Comment by martysweet** [comment]
@RazzM13 Yeah, I was just about to comment that.

Looks like fresh builds are working fine on CircleCI so not sure why it would be happening in your environment. Let me know what you discover!

**Comment by RazzM13** [comment]
I believe that the core of the problem is the depedency cache system due to the fact that it checks the `package.json` file for changes, when perhaps it should be using `package-lock.json`.

**Comment by martysweet** [comment]
Thanks @RazzM13, the patch has now been merged into master. Will look into `package-lock.json`!
