### ISSUE TITLE
Uncaught exception behavior

### ISSUE THREAD

**Issue by RazzM13** [martysweet/cfn-lint#122]
Apparently, when the `cfn-lint` cli executable encounters an uncaught exception during the `validate` command, it outputs the associated stack trace.
 
Perhaps it would be more consistent to output `Unable to parse template!` instead of the rather lengthy stack trace.

**Comment by martysweet** [comment]
Agreed. This can also be merged with issue #121 to resolve the exit code issue.

Stack traces can be useful for debugging, we still need a method to see this to work out whats gone wrong.

**Comment by martysweet** [comment]
I think adding a `--verbose` flag would be good, this would then provide further scope if we wish to return other information to the user during runtime.
