### ISSUE TITLE
CircleCI is failing to build

### ISSUE THREAD

**Issue by martysweet** [martysweet/cfn-lint#145]
Looks to be since npm version went from `npm@5.8.0` to `npm@6.0.0`.

Would be nice to work out _why_, instead of pinning versions :grinning:

**Comment by RazzM13** [comment]
I've just tested it out with node `9.11.1` and npm `6.0.0` and the tests ran perfectly. CircleCI is currently having some [issues](https://status.circleci.com/incidents/xjxj6b143m0j) that might pertain to the current build failure(s).

**Comment by RazzM13** [comment]
In regards to the above mentioned, I've just opened a new issue with `npm` -> npm/npm#20425.

**Comment by martysweet** [comment]
Hmm, I tried to bump the circleci node version to the latest LTS in #144, and started to get a different error

**Comment by RazzM13** [comment]
Hi @martysweet, just fixed it in PR #146.
PS: Nice catch with the npm version change :smiley:! should `cfn-lint` stop supporting *NodeJS* versions under `6.0.0` as well ?

**Comment by martysweet** [comment]
Horray! Great stuff - thanks!

I am happy to keep supporting Node 4 until it starts causing us significant problems (as it only goes EOL at the end of this month), those tests you made will certainly help us catch anything.
