### ISSUE TITLE
🐛Error: No such resource AWS::EKS::Cluster

### ISSUE THREAD

**Issue by A-Tokyo** [martysweet/cfn-lint#181]
First, I'd like to say Amazing work 👏 🎩 

---
name: 🐛 Bug Report
about: If something isn't working as expected 🤔.

---

## Bug Report

**Current Behavior**
Cloudformation templates that make use of AWS's EKS (Kubernetes) throw `Error: No such resource AWS::EKS::Cluster`.

**Expected behavior**
AWS::EKS Resources should be parsed successfully.

**Comment by martysweet** [comment]
@A-Tokyo, this should now work in v1.7.4, let us know if you have any issues!

**Comment by A-Tokyo** [comment]
@martysweet Thanks man! Working flawlessly ✨
