### ISSUE TITLE
NPM test exit code incorrect

### ISSUE THREAD

**Issue by martysweet** [martysweet/cfn-lint#191]
@RazzM13 looks to be these tests which are causing the issues with the exit status code. If they are removed the exit code on `npm test` works as expected. Any ideas?

https://github.com/martysweet/cfn-lint/blame/master/src/test/indexTest.ts#L168-L240

**Comment by RazzM13** [comment]
Hi @martysweet, mia culpa, sorry for blowing up the tests for everyone :)
I've taken the liberty of splitting the CLI tests into two sections so that there's a clear distinction between them and fixed the problem by ensuring the tests cleanup after themselves.
Hope it's ok.

**Comment by martysweet** [comment]
Awesome, thanks @RazzM13
