### ISSUE TITLE
Reports property as invalid when it is valid

### ISSUE THREAD

**Issue by aap69** [martysweet/cfn-lint#201]
When validating a cfn template with a resource of type AWS::EC2::SpotFleet, I get the following error:

cfn-lint error:

2018-10-30T06:42:04.6891330Z 1 crit
2018-10-30T06:42:04.6891404Z Resource: Resources > spotFleet > Properties > SpotFleetRequestConfigData > LaunchTemplateConfigs
2018-10-30T06:42:04.6891539Z Message: LaunchTemplateConfigs is not a valid property of AWS::EC2::SpotFleet.SpotFleetRequestConfigData
2018-10-30T06:42:04.6892453Z Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-spotfleet.html
2018-10-30T06:42:04.6892703Z 
2018-10-30T06:42:04.6892914Z Template invalid!

template snippet for resource:

  spotFleet:
    Type: AWS::EC2::SpotFleet
    DependsOn:
    - spotFleetRole
    Properties:
      SpotFleetRequestConfigData:
        AllocationStrategy: "lowestPrice"
        IamFleetRole:
          Fn::GetAtt:
          - spotFleetRole
          - Arn
        ReplaceUnhealthyInstances: true
        TargetCapacity:
          Ref: TargetCapacity
        ValidFrom: !Ref FleetStart
        ValidUntil: !Ref FleetStop
        TerminateInstancesWithExpiration: true
        LaunchTemplateConfigs:
        - LaunchTemplateSpecification:
            LaunchTemplateName:
              Ref: LaunchTemplateName
            Version:
              Ref: LaunchTemplateVersion
          Overrides:
          - InstanceType: !Ref InstanceType
            SubnetId: !Select [ 0, !Ref SubnetIds ]
            WeightedCapacity: 1
          - InstanceType: !Ref InstanceType
            SubnetId: !Select [ 1, !Ref SubnetIds ]
            WeightedCapacity: 1
          - InstanceType: !Ref InstanceType
            SubnetId: !Select [ 2, !Ref SubnetIds ]
            WeightedCapacity: 1

AWS cfn documentation shows valid property LaunchTemplateConfigs:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-spotfleet-launchtemplateconfig.html

The template launches successfully, as expected.

**Comment by martysweet** [comment]
Hi @aap69, can you test this with the latest version of cfn-lint v1.9.1. The aws cloudformation specification has just been updated. Thanks!

**Comment by aap69** [comment]
Hi @martysweet, v1.9.1 has fixed this issue. Many thanks (: 👍
