### ISSUE TITLE
Fn::Sub variable escaping not supported

### ISSUE THREAD

**Issue by wannesvc** [martysweet/cfn-lint#211]
Basically the following resolves as an error (while the template deploys without any issues):

To write a dollar sign and curly braces (${}) literally, add an exclamation point (!) after the open curly brace, such as ${!Literal}. AWS CloudFormation resolves this text as ${Literal}.

[https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html](url)

**Comment by wannesvc** [comment]
My bad!! it is indeed fixed, sorry for wasting your time and thanks for building this great tool!

**Comment by martysweet** [comment]
No worries! Thanks :smile:
