### ISSUE TITLE
Support custom resources

### ISSUE THREAD

**Issue by nikolay** [martysweet/cfn-lint#28]
Resource type of `Custom::*` is valid, but `cfn-lint` fails it.

**Comment by martysweet** [comment]
Thanks @nikolay. A patch for this would probably be best suited in the https://github.com/martysweet/cfn-lint/blob/master/src/resourcesSpec.es6 file. Where any Resource Type starting with Custom:: is caught and returned properly. 

When a "Custom::" resource type is found, the code should lookup `AWS::CloudFormation::CustomResource` within the resource spec json. The current property check should also read the `AdditionalProperties` attributes of the resource specification file to prevent unknown property errors when using a custom resource (or any other resource which allows custom properties).

I will have a look into this next week.

**Comment by martysweet** [comment]
Hi @nikolay,

The changes to make this possible are now available in version 1.0.14. Please update and try again!

Closing this issue 😄
