### ISSUE TITLE
Doesn't handle the output section in a cloudformation stack

### ISSUE THREAD

**Issue by JermilaPaulDhas** [martysweet/cfn-lint#39]
Invalid references made in the output section of the cloudformation stack is not handled.

**Comment by martysweet** [comment]
@JermilaPaulDhas Thanks for reporting this. The issue appeared to be references/getattributes not being validated within the Intrisinic Sub function. A fix has been released in v1.1.3, which you can download from npm now.

If the problem persists, please provide an example template with the issue. 

PR: #40
