### ISSUE TITLE
CLI exit codes

### ISSUE THREAD

**Issue by mithun** [martysweet/cfn-lint#47]
Can the CLI provide a non-zero exit code for invalid templates, and optionally when `crit` and `warn` results exist?

This will allow cfn-lint to be used in a CI process that can abort/fail when invalid templates and/or critical errors are present

**Comment by martysweet** [comment]
Thanks @mithun, if you have a chance to make a PR that would be great.

Marty

**Comment by martysweet** [comment]
Merged in #62
