### ISSUE TITLE
Validation without parameters

### ISSUE THREAD

**Issue by aarongorka** [martysweet/cfn-lint#57]
I'd like to be able to locally validate the syntax of my CloudFormation templates on PRs. I don't have any requirements to validate parameters and it's not realistic for me to document the parameters of all the templates I have. It would be quite useful to skip that option and any validation that depends on passing through parameters.

**Comment by martysweet** [comment]
@aarongorka The AWS CLI has a validate-template command which will do a simple check http://docs.aws.amazon.com/cli/latest/reference/cloudformation/validate-template.html, however this tool doesn't check the validity of properties for resources.

cfn-lint depends on input parameters as it resolves all the references to ensure you haven't missed something, it will then check the properties of each resource specified - something which the aws cli doesn't do.

If parameter defaults were read in (I'm not sure if this is currently the case), would this satisfy your requirement? Then you would get a full test without having to manually specify parameters on the command line.

**Comment by aarongorka** [comment]
@martysweet the AWS CLI does validation on Amazon's side, meaning it's really slow to check lots of templates and relies on having credentials (which is a bit of a pain when you're using assume role).

Using parameter defaults could actually be a viable workaround, I hadn't considered that. I think a lot of my templates will having defaults missing so it'd still be nice to be able to do limited validation without them. I'll investigate how much work it would be to add defaults and if it's realistic I may go with that solution for the time being.

**Comment by martysweet** [comment]
@aarongorka I'm going to close this issue, feel free to reopen it if you feel there is a missing feature!
