### ISSUE TITLE
Feature request - be able to call as a node library and access stack outputs

### ISSUE THREAD

**Issue by akdor1154** [martysweet/cfn-lint#78]
I am working to integrate this tool with [Sceptre](http://github.com/cloudreach/sceptre), which is a tool to orchestrate a set of stacks being deployed at once. I am not attempting to actually modify sceptre to call cfn-lint directly, but I am writing a local validation tool that runs `cfn-lint` on all stacks in a Sceptre environment.

It would be really helpful to be able to do require('cfn-lint') in a node bridging script, as it's difficult to parse CLI output (and I guess this is not maintained as part of the concept of stable API, which is fair enough..)

require('cfn-lint/validator') does currently work as a workaround.

In addition, and for the same reason, it would be great to have access to computed stack outputs in the errorObject.

I currently have a branch that does both of these; would this functionality be considered?

**Comment by martysweet** [comment]
Yes, this is something I have been wanting to do but haven't got around to yet :+1:
