### ISSUE TITLE
Feature request - more control over parameter validation

### ISSUE THREAD

**Issue by akdor1154** [martysweet/cfn-lint#79]
It would be useful if cfn-lint could be ran in a sort of 'strict mode' that it would create an error if a parameter was missing and not provided as a Default or on the CLI, instead of (or maybe as well as) proceeding with a mocked value.

Perhaps an optional `options` argument passed to `validateFile` to switch behaviour.

Would you accept this?

**Comment by martysweet** [comment]
Doesn't this already happen if the missing Parameter is used?

**Comment by akdor1154** [comment]
Nope, it gets a value of `let parameterRefAttribute = \`string_input_${param}\`;`. You do currently get a roundabout warning if the parameter then gets used in an Arn property (or I guess for a List or Map), but this is based on type mismatch, not because the parameter has been mocked.

**Comment by martysweet** [comment]
Good point, something flaggable would be great.
